## Backpropagation Using PyTorch
y=x^2 

In [12]:
import torch

In [13]:
x=torch.tensor(4.0,requires_grad=True)
x
#requires_grad needed to compute gradients for backpropagation
#only floating point numbers can get gradients

tensor(4., requires_grad=True)

In [14]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [15]:
#Backpropagation y=2*x
y.backward()

In [16]:
print(x.grad)  #Output of backpropagation of y=x^2: 2x = 2.4 =8

tensor(8.)


In [27]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [28]:
#y=x^3 + x^2
#Backpropagation: y=3x^2 + 2x
y=torch_input**3+torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [30]:
z=y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [31]:
z.backward()

In [33]:
 torch_input.grad  #y=3x^2 + 2x for each element

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

In [36]:
print('Done')

Done
