In [1]:
import torch

In [2]:
torch.__version__

'1.10.1'

In [3]:
import numpy as np

In [5]:
lst=[3,4,5,6]
arr=np.array(lst)

In [7]:
arr.dtype

dtype('int32')

## Convert Numpy to Pytorch Tensors

In [8]:
tensors=torch.from_numpy(arr) #disadvantage of from_numpy:Array and tensor use same memory location
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [9]:
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [10]:
tensor_arr=torch.tensor(arr) #Solves above problem
tensor_arr

tensor([3, 4, 5, 6], dtype=torch.int32)

In [12]:
tensor_arr[3]=20
tensor_arr

tensor([ 3,  4,  5, 20], dtype=torch.int32)

In [15]:
print(torch.zeros(2,3,dtype=torch.float64))
print(torch.ones(2,3,dtype=torch.int64))


tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]])


## Arithmetic Operations

In [21]:
a=torch.tensor(np.arange(1,4))
b=torch.tensor([2,4,6])
a+b

tensor([3, 6, 9])

In [22]:
 torch.add(a,b)

tensor([3, 6, 9])

In [25]:
torch.add(a,b).sum()

tensor(18)

## Dot Products and Multiplication

In [28]:
x=torch.tensor([3,4,5],dtype=torch.float)
y=torch.tensor([4,5,6],dtype=torch.float)
print(x.mul(y))   #Multiplication
print(x.dot(y))   #Dot product

tensor([12., 20., 30.])
tensor(62.)


In [33]:
a=torch.tensor([[1,4,2],[1,5,5]])
b=torch.tensor([[5,7],[8,6],[9,11]])   #2D array
torch.matmul(a,b) #OR a@b   for Matrix Multiplication

tensor([[55, 53],
        [90, 92]])

In [35]:
a@b

tensor([[55, 53],
        [90, 92]])